### PR TITLE
Creating AB Test guides/practices

### PR DESCRIPTION
**Pull request by bensaufley**
Just the bare bones right now, and of course open to suggestions.

@akainic and @yihanli suggested possibly having an indicator in the name of the control leg of a test to specify that it is the control – e.g., starting that leg with an underscore (`_shown`, `hidden`). The control should be clear from the code (as specified in this PR) but from Goat, it's less clear. What do you think, @kylepfeeley?

cc @fishermanswharff @melissacavallaro

### CODE REVIEW

**Comment by kylepfeeley** [comment]
Looks great! cc @mikeraimondi @AlbertGrimley

**Comment by kylepfeeley** [comment]
@bensaufley @akainic @yihanli I'm fine with starting the test leg name with an underscore to indicate control.

**Comment by bensaufley** [comment]
@yihanli does an underscore work for you? I just threw that out there as a possible identifier that wasn't going to make the value significantly longer

**Comment by bensaufley** [comment]
@akainic, @kylepfeeley I went to add a line stipulating the _ prefixing of Control values, but I realized it may be a bit more complex than that, considering that often the AB Test value can (and should be able to) be used as a direct output or otherwise passed on, rather than just used as a flag. E.g.:

```haml
= get_ab_test_value('headline_text', 'Get Your Quote'), # or View Now, e.g.
-# or
- ab_quote_name = get_ab_test_value('quote_name', 'Quote') # or Estimate, e.g.
Get your free #{ab_quote_name} now!
```

What do you think? The easy thing would be to just prefix these and then strip the preceding underscore as needed – `ab_quote_name = get_ab_test_value('quote_name', '_Quote').sub(/^_/, '')` – but that's pretty ugly.

I wonder if @mikeraimondi has any thoughts on this, as well?

**Comment by mikeraimondi** [comment]
@bensaufley there is a feature in the pipeline to add "structured AB tests" for content swaps like the example you provided. In the near future, these kind of tests will be handled differently. I think prefixing makes sense in the long term.

**Pull request merged**
