### PR TITLE
Prefer `size` for AR collections

### PR DESCRIPTION
**Pull request by mikeraimondi**

### CODE REVIEW

**Comment by bensaufley** [comment]
:+1:

**Comment by crberube** [comment]
YES * 1000

**Comment by bensaufley** [comment]
I'm entirely in favor of this, but what happened to leaving PRs open for a week?

**Comment by mikeraimondi** [comment]
@bensaufley it was open for 24 days...

**Comment by bensaufley** [comment]
Whuh –

Haha you're right. Sorry, I saw this in my inbox with the PR above it (dunno if I didn't get it, or if the threading got messed up) and it looked like it got submitted and merged all this morning.

…carry on, then.

**Pull request merged**
