### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by germsvel**
Add Class Structure to Ruby Guide

### CODE REVIEW

**Comment by bensaufley** [comment]
@AlbertGrimley @mikeraimondi I'm particularly interested in your feedback here.

In the past, in my own work, I've actually swapped class and instance methods: instance, class, private/protected. I don't _entirely_ know why I've chosen that way – I think because instance methods tend to be more commonly-referenced, and thus it seems right to show them first? But I'm fine with this being the standard. This also makes sense.

**Comment by crberube** [comment]
The official ruby style guide that is used in code validation tools etc. says to put class methods first. https://github.com/bbatsov/ruby-style-guide#consistent-classes

This is the way I have always seen it done when programming myself. In fact I think we should just adopt the official guide as our guide for ruby.

**Comment by mikeraimondi** [comment]
Personally, I don't care so much where the class methods are located as long as they are *contained*. In other words, they must not be intermingled with instance methods.

That in mind, instead of this:

```ruby
def self.foo
end

def self.bar
end
```

I prefer this:

```ruby
class << self
  def foo
  end

  def bar
  end
end
```

This way, containment is enforced by syntax.

**Comment by bensaufley** [comment]
I like @mikeraimondi's point. I'd say we combine it with @germsvel's ordering stipulation, just so that there is a "right" way. So:

```rb
def thing
  class << self
    def class_method
    end
  end

  def instance_method
  end
end
```

**Comment by crberube** [comment]
Again, I feel like we should follow the official guides that syntax-checking tools in ruby use (such as rubocop or hound). The guide states: Avoid class << self except when necessary, e.g. single accessors and aliased attributes.

class << self is useful if you need to make a private class method for example, because you can't do that otherwise. However some downsides to class << self if that if you have a lot of methods it is not immediately clear they are class methods because the containing block could be off screen. It also makes it harder to search for class methods: you can't just grep for ```self.```.

class << self also sets self to the class (singleton class) inside the block, something that you may not want to do. In reality, even though they act similarly they are not the same thing.

**Comment by bensaufley** [comment]
I mean, I don't tend to muck around in classes too much as a UX guy, so I'll defer to the Technical Lead for Consumer-Facing Applications (or whatever) @mikeraimondi. But here are my thoughts:

> it is not immediately clear they are class methods

Proper indentation should lessen this, but I can see this being a small inconvenience.

> It also makes it harder to search for class methods

Searching should be rendered unnecessary because they should all be grouped at the top of the class. Is there a scenario where you're searching in an entire project for `self.`?

Most syntax-checking tools can be customized, as well. I'm not saying we should go against them just to go against them, but if there's a preference to do things differently, tools can be adapted. I think your points are valid, @crberube . But I don't think any of them particularly convince me, personally, that we _shouldn't_ use `class << self`.

**Comment by crberube** [comment]
@bensaufley Did you see my edit with the code sample? It changes scope.

I admit that this is not a common case but there are technical differences between the two approaches and I don't think it makes sense to say always use this one way when they don't do the same thing, no matter how minor.

**Comment by germsvel** [comment]
@bensaufley I agree with @crberube on all accounts. 

And to your two points, 

> Proper indentation should lessen this, but I can see this being a small inconvenience.

Proper indentation isn't always enough, especially when you are dealing with larger classes. 

> Searching should be rendered unnecessary because they should all be grouped at the top of the class.

When working with larger classes, searching inside the class for the method is the fastest way to get to the code you are looking for even if they are all grouped together.

**Comment by bensaufley** [comment]
Honestly, I'd imagine the `class << self` result is what I'd want and expect from a self method. I'm also a little confused – `c` is an instance, is it not?

If I had:

```rb
VARIABLE = "Wing"

class Thing
  VARIABLE = "Wang"

  class << self
    def x
      puts VARIABLE
    end
  end

  self.y
    puts VARIABLE
  end
end
```

And I ran:

```rb
Thing.x
Thing.y
```

I'd expect both to give me "Wang". 

I don't know. Again, I'll defer to @mikeraimondi

**Comment by bensaufley** [comment]
> When working with larger classes, searching inside the class for the method is the fastest way to get to the code you are looking for even if they are all grouped together.

@germsvel you can still search for the method, though… I don't understand how this stops that? There's a scenario where `self.method` and `method` are both defined… in which case you'd have _two_ instances of `def method`?

I honestly don't have a dog in this fight. I'm just the kind of person who takes up arguments because I see them, hahah. I still don't really see the disadvantage here. The change of scope is probably the biggest _effective_ change, and probably the most persuasive argument. Even if I don't entirely get why you'd want to have an external var referenced over an internal one…

**Comment by mikeraimondi** [comment]
For me, and I should stress that this is all personal preference, I find having to scan through a class to find all the class methods to be more problematic and time-consuming than any of the downsides brought up so far. I'm all in favor of whichever solution minimizes the chances that class methods will be interspersed with instance methods.

That said, this feels like one of those debates that probably consumes more time than is likely to be saved by any of the proposed solutions :)

**Comment by bensaufley** [comment]
The best kind of debate

**Comment by crberube** [comment]
Just to note I absolutely think that even if self.method_name is used, they should all be in one place.

**Comment by bensaufley** [comment]
Yeah I think that was the idea of the initial PR. self methods at the top of the class.

**Pull request merged**
