### PR TITLE
Add preference for decorators over helpers

### PR DESCRIPTION
**Pull request by mikeraimondi**
IMO, here are a few of the points in favor of decorators:

* Composable. Decorators can be inherited and mixed in to share functionality across classes.
* Namespaced. Less concern about method names overlapping/overwriting.
* Understandable. It's clear where a decorated method is defined. Helpers could be defined in any helper file.
* Testable. A spec file for a single helper module may involve a large amount of set-up with different models, controller callbacks, etc. Helper spec files are written much the same as unit tests. We do not assume that controller helper methods are available or that callbacks have been run.
* Performant. Helpers are automatically `include`'d in every controller and view. This adds overhead. Decorators must be explicitly invoked.

I've experienced a couple of pain points:

* Modifying collection decorators can lead to weird errors. For this reason, we must [decorate our models just before using them in a view](https://github.com/drapergem/draper#when-to-decorate-objects).
* Pagination. [See here](https://github.com/drapergem/draper#using-pagination).

Opinions? Thoughts?

### CODE REVIEW

**Comment by bensaufley** [comment]
That first pain point is a big one for me. Makes HAML messier (and it's already quite messy), makes object references sometimes less readable.

Which is why I think decorators have a solid purpose but I'm rarely comfortable with setting up a decorator & decorating an object for, say, one thing on a page, _especially_ when it's not really decorative (e.g. a value or Boolean, or other information).

I'm ready to be convinced, but I'm not 100% in favor of "Prefer decorators over helpers" because, IMO, they serve different purposes.

**Comment by mikeraimondi** [comment]
@bensaufley can you give an example of a use case where a helper is preferable to a decorator?

**Comment by bensaufley** [comment]
`post_form_impression_path?` in `exits_helper` seems like an OK one to me.

My understanding of Draper and decorators is that they were built to keep from cluttering the model with view-oriented code. The model may have `user.profile_photo` but a decorator would be the right place for `user.thumbnail`, if `thumbnail` outputs `<a href="#{@user}" class="thumbnail"></a>"`.

A Boolean like `post_form_impression_path?` relates to the controller and is used `@impression_path` is shared all over the place. It doesn't seem like it belongs on, say, `ad`. It doesn't appear there _is_ an `Exit` model for it to even be discussed. If there were, I might argue it should be a model method.

There are many other helpers that don't, to me, fit the idea of what decorators are for ("decorating" a model in a view), but I think this is at least an OK example.

**Comment by mikeraimondi** [comment]
For reference, here's the method definition:

```ruby
  def post_form_impression_path?
    @impression_path == Enums::ImpressionPath::TYPE_POST_FORM
  end
```

IMO, `post_form_impression_path?` is a pretty bad method because it relies on an unrelated instance variable being set. This is an example of global state being used where it would be easy to rewrite as a pure method that assumes no global state:

In `Enums::ImpressionPath`

```ruby
def self.is_post_form_impression_path?(path)
  path == TYPE_POST_FORM
end
```

This is better because it is clear when `is_post_form_impression_path?` is called that we are checking the value passed to it. The previous version leads to hunting through helper files looking for a method definition so we can tell what's being checked.

**Comment by bensaufley** [comment]
So the implementation becomes `Enums::ImpressionPath.is_post_form_impression_path?(@impression_path)`? Or, what? That seems longer, less clear, less helpful to me. And it still eventually relies on `@impression_path` or some other helper/method that retrieves the impression path.

**Comment by mikeraimondi** [comment]
Yes, `Enums::ImpressionPath.is_post_form_impression_path?(@impression_path)`. Verbosity is not always bad. In this case, I know right away:

1. Where the method is defined
2. What the method relies upon

To me this is vastly preferable to a method with unclear origins and requirement.

**Comment by bensaufley** [comment]
That's not really compelling to me. `is_post_form_impression_path?` as a helper is perfectly clear, and clearly a helper that tells you it's checking that the impression path (`@impression_path`) is post form (which happens to be defined by `Enums`, as can be seen if you view the helper). Investigating the method will show you essentially what your version shows, and exactly what the helper method's name implies, and tell you the same things. Finding a helper method shouldn't be considered a pain point. In RubyMine, it's as simple as Cmd+Click – of course I'm not relying on everybody using the same tools, but being able to find methods from their usage is part of a programmer's basic toolkit regardless of the environment.

Honestly, it seems like just un-helperizing this would be more helpful than creating a verbose decorator method to run that test. Just throw `@impression_path == Enums…` back into the code. Would take up about the same amount of space, be equally rememberable and clear. I 100% agree that sometimes verbosity is better. I just don't find this case to necessarily be one of those times.

`@impression_path` is defined at some point from `params[:path]` for re-use throughout Lynx. If we want to rethink some of these instance variables (`@arrival` and `arrival` have caused me trouble lately), that seems like maybe a bigger discussion? But I don't think they're going away very soon and I don't think that essentially unwrapping the helper is … helpful, here.

Helpers aren't an antipattern. They were built into Rails for a purpose, and this seems like a perfectly good application of that purpose.

**Comment by germsvel** [comment]
I tend to agree with Mike on this one. I think it is better to _prefer_ decorators. But I do think helpers have their place. 

Something I find helpful in determining if I should move a method from a helper to a decorator is to see if (a) the helper is very hard to test or (b) if it has feature envy, referencing the same object several times. Those two code smells usually point me to move it to a decorator.

**Comment by bensaufley** [comment]
I think "prefer decorators over helpers" is too broad, though. I'm fine with and in fact _support_ preferring decorators when they're the rational choice, but that's more, like … "Understand the distinction between decorators and helpers and use each as appropriate" than "prefer one over the other" – I don't think they are interchangeable things and this reads to me like "Prefer `map` over `collect`," a guide rule that says which of two identical methods to use for consistency.

**Comment by germsvel** [comment]
I see your point Ben. The word "prefer" has a particular meaning in our guides. Is there another word we have in the guides to "suggest" to use decorators _first_, and if it doesn't fit use helpers? I do think we tend to reach for helpers and we use them too much in lynx.

A somewhat tangential point, but I think it makes the helper problem worse: I've seen a lot of controller methods defined as helpers when I think they should be defined elsewhere (like in decorators). Can we at least say, "prefer to use decorators, or helpers, over defining helper methods in controllers"?

**Comment by bensaufley** [comment]
I think the original intent, prompted by @jacobcmurphy's PR (?), was to actually set some guidelines about when to prefer each. Because they are not _the same_ but do serve _similar_ purposes, and could sometimes be confused. In outlining that, we could easily specify things like you've suggested.

**Comment by mikeraimondi** [comment]
Maybe someone can help me out here, but I'm still struggling to think of a single situation where a helper would be preferable to a decorator. Does anyone have an example?

**Comment by bensaufley** [comment]
I maintain that `post_form_impression_path?` is a good example, especially with the way Lynx is currently built.

Draper was created to get the view-related model-based methods out of the model and/or the helpers – ways to represent a model or its attributes in the view without clogging up the view, or putting view code in the model. I don't believe it was created to outright supplant helpers. I _do_ think there are a lot of Lynx helpers currently that would be better applied as decorator methods (`theme_button`, `theme_link` etc are _perfect_ examples), but I reject that a decorator serves the same universal purpose as a helper. As I said, helpers are a core part of Rails and are worth utilizing when appropriate.

**Comment by mikeraimondi** [comment]
Coffeescript and turbolinks are equally core parts of Rails, and we're moving away from the former and not even using the latter. That a component is included with the framework is not a good reason to use that component.

Putting that aside, if we're going to resolve this disagreement in any sort of constructive way, we'll need to come together on criteria for when to use helpers over decorators. Suggestions?

**Comment by AlbertGrimley** [comment]
This is an expensive disagreement. Can we please move on?

**Comment by mikeraimondi** [comment]
You haven't heard the last from
m
e
e
e
e
e
.
.
.
e
e
.
.

**Pull request closed without merging**
