### PR TITLE
Propose using `let` over `before` in test setup

### PR DESCRIPTION
**Pull request by germsvel**
1. `let` creates lazily-evaluated local variables
2. `before` blocks use instance variables. Those allow for typos since they are initialized to `nil` when first referenced. 
3. It is (as far as I know) a best practice in the ruby community

### CODE REVIEW

**Comment by bensaufley** [comment]
This isn't really my milieu but is there a time when `before` is reasonable? It appears they have different functionalities and yeah, for the most part, `let` looks like the better choice. Just wondering if it's worth outlining a scenario where `before` is the more reasonable option… aside from aliased methods, I'm not a fan of saying "Always use method A over method B" – presumably both have their uses, even if one is (as stated here) "preferred."

**Comment by germsvel** [comment]
I think we should use `before` only when we need to do some setup that does not require access to those variables later in the tests. e.g.

```
let(:ab_test) { AbTest.new }


before do 
  ab_test.resolve! # suppose you can't do this in the setup
end
```

I can update this PR or submit a different one with that info if it seems reasonable.

**Comment by bensaufley** [comment]
I'd say tacking it on to this one would be fine.

**Comment by mikeraimondi** [comment]
:+1: IMO, we should prefer `let` for assignments, and generally only use `before` for side-effect-y stuff. mutating a local variable, changing some piece of global state, etc.

**Comment by germsvel** [comment]
I agree with @mikeraimondi. And I like his choice of words. I'll try to update to include some of that.

**Comment by bensaufley** [comment]
@germsvel if you want to update this with whatever word changes you wanted to make, we can merge it

**Comment by germsvel** [comment]
@bensaufley will do that right now. Thanks for the reminder

**Pull request merged**
