### PR TITLE
Prefer single quotes in JavaScript

### PR DESCRIPTION
**Pull request by lizvdk**
Updates the JavaScript quote guideline.

### CODE REVIEW

**Comment by crberube** [comment]
I'm just curious why we're changing this? I've always gone by the jQuery style guide:
http://contribute.jquery.org/style-guide/js/#quotes

**Comment by lizvdk** [comment]
@crberube I have received PR comments telling me to use single quotes where possible in js.

**Comment by mikeraimondi** [comment]
I'd like to hear @bensaufley's feedback, but personally I agree with this PR. It saves keystrokes and it's consistent with our Ruby style guidelines.

**Comment by bensaufley** [comment]
:+1: yes

**Pull request merged**
