### PR TITLE
Propose local variables in partial view templates

### PR DESCRIPTION
**Pull request by germsvel**

### CODE REVIEW

**Comment by bensaufley** [comment]
My question is, does this count semi-partials like, say, `_s1` of a form? Technically, `index` is calls `_s1` as a partial, but essentially, `_s1` is the root view.

**Comment by germsvel** [comment]
I don't think it's that hard to have `index` pass on the instance variables to all those semi-partials. But I could see us making an exception there if we were having complications. Still, I would start with trying to pass all the variables, and if there's some very good reason why we shouldn't do it, then that's okay. In other words, I'd suggest following the rule and only breaking it if we have good cause for it.

**Comment by bensaufley** [comment]
Alright. I'm game. It'll take a little refactoring but it should be manageable.

**Comment by mikeraimondi** [comment]
:+1: Glad to have a consensus on this.

**Pull request merged**
