### PR TITLE
Propose avoidance of common setup unless shared

### PR DESCRIPTION
**Pull request by germsvel**
Propose that we avoid using `let` and `before` when the variables setup are not used throughout all examples in that example group (an example group is defined by either `describe`, `context`, or `feature`). 

Why? 
1. It obscures tests unnecessarily in the name of DRYness. It becomes very difficult to know which tests need what part of the "common" setup. 
2. It slows tests down by creating data that is unneeded for some test examples. This is especially true when using `before` blocks or `let!`. 
3. It makes tests more fragile by causing some tests to be dependent on setup that they should not be.

### CODE REVIEW

**Comment by bensaufley** [comment]
Does this hold true for vars that are used in, say, all but _one_ spec? I'm just wondering where the tipping point is. I thought the idea of `let` was the it doesn't get run unless the variable is used?

**Comment by germsvel** [comment]
I could see why some people might want to use it when all but _one_ spec use the default setup. That's why I chose to use "Avoid" instead of "Don't" because I understand there might be a scenario where you really want to just extract that local var to the common setup. 

That being said, I have seen people use the before setup to set up some sort of base state and then modify it in every test. For example, you might have something like this: 
```
describe Model do 
  let(:object) { FactoryGirl.create(:model_name, :with_association) }

  it 'does something' do 
    object.update_attribute(:hello_world, true)

    expect(object).to have_key "hello world"
  end

  it 'does not do something' do 
   object.update_attribute(:hello_world, false)

    expect(object).not_to have_key "hello world"
  end

  it 'is nil when association is nil' do 
   object.world_object = nil

    expect(object.hello_world).to be_nil
  end
end
```

I think that is not the best use of `let`. It would be cleaner to just do the needed setup in every test. Also, a better solution to those types of setup problems is often a better factory setup. For example, we could write the above like this: 
```
describe Model do 

  it 'does something' do 
    object = FactoryGirl.create(:model_name, :with_association, :hello_wordly)

    expect(object).to have_key "hello world"
  end

  it 'does not do something' do 
       object = FactoryGirl.create(:model_name, :with_association)

    expect(object).not_to have_key "hello world"
  end

  it 'is nil when association is nil' do 
    object = FactoryGirl.build(:model_name)

    expect(object.hello_world).to be_nil
  end
end
```

This is obviously a simplified scenario, but imagine you have 3-5 or even more `let` statements at the top, and perhaps even a `before` block doing some additional setup. Some of your tests use `let` statements 1, 3, 4, others use 1, 2, 5, maybe one test uses all 5 `let` statements, but you have no idea which ones use which. And then you come along and you want to add a test. Are you going to look at those 5 and see which apply to your test? Probably not. Most likely you're just going to add another `it` block and take everything up there as given. I think that's how tests start getting brittle.

**Comment by bensaufley** [comment]
Makes sense to me.

**Comment by mikeraimondi** [comment]
:+1: Yup!

**Pull request merged**
